description     "Duet host-side automatic display rotation"
author          "duet-autorotate"

start on started system-services
stop on stopping system-services
respawn
respawn limit 10 60

exec /usr/bin/python3 /usr/local/duet-autorotate/duet-autorotate daemon
